#ifndef NOTIFY_PARSE_ENV_H
#define NOTIFY_PARSE_ENV_H

#define ENV_PREFIX "NOTIFY_"
#define PARSE_ENV(VAR) if(getenv(ENV_PREFIX # VAR)) VAR = atoi(getenv(ENV_PREFIX # VAR))
#define PARSE_ENV_STR(VAR) if(getenv(ENV_PREFIX # VAR)) VAR = getenv(ENV_PREFIX # VAR)
static inline void parseEnv() {
    PARSE_ENV(ACTION_BUTTON);
    PARSE_ENV(BG_COLOR);
    PARSE_ENV(BORDER_COLOR);
    PARSE_ENV(BORDER_SIZE);
    PARSE_ENV(DISMISS_BUTTON);
    PARSE_ENV(FG_COLOR);
    PARSE_ENV(FIXED_HEIGHT);
    PARSE_ENV(HEIGHT);
    PARSE_ENV(TIMEOUT);
    PARSE_ENV(WIDTH);
    PARSE_ENV(X);
    PARSE_ENV(Y);
#ifndef NO_MSD_ID
    PARSE_ENV_STR(MSG_ID);
#endif
#ifndef DISALLOW_OVERLAP
    PARSE_ENV_STR(LOCK_FILE);
#endif

    PARSE_ENV(FONT_SIZE);
    PARSE_ENV_STR(FONT_NAME);
}
#endif

